project:
  type: website

website:
  title: "Risk Adjustment Network"
  favicon: "favicon.ico"
  
  page-footer: 
    center: 
      - text: "The website is proudly powered by Stam Online"

format:
  html:
    css: style.css

editor: source
