project:
  type: website

website:
  title: "Risk Adjustment Network"
navbar:
  left:
  - href: index.qmd
    text: Home
  - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

