project:
  type: website

website:
  title: "Risk Adjustment Network"
  favicon: "favicon.ico"

format:
  html:
    css: css/styles.css
    grid: 
      sidebar-width: 0px
      body-width: 800px
      margin-width: 0px
      gutter-width: 0rem
    link-external-icon: true
    link-external-newwindow: true

editor: source
