---
title: "Risk Adjustment Network"
subtitle: "A collaborative of economists on the science and practice of regulated competition in health insurance" 
---
  
# History
  
  Fall 2000, the Risk Adjustment Network (RAN) was founded by health economists from The Netherlands, Belgium, Germany, Israel and Switzerland. Currently, also Ireland, Australia and the USA are represented in the RAN.

# Mission statement

Our mission is to endorse an international exchange of scientific results in the field of risk equalization systems and to enhance the usability of this knowledge in the political process. We also share our knowledge about the science and practice of regulated competition in health insurance in general and compose international comparison papers on specific subjects.

# Profiles of members

- [Armstrong, John (IE)](https://ie.linkedin.com/in/john-armstrong-ba22a31)
- [Beck, Konstantin (CH)](https://www.unilu.ch/fakultaeten/wf/professuren/titularprof-dr-konstantin-beck/)
- [Brammli-Greenberg, Shuli (IS)](https://sites.google.com/view/shuli-brammli-greenberg)
- [Buchner, Florian (DE)](http://mitarbeiter.fh-kaernten.at/florianbuchner/)
- [Douven, Rudy (NL)](http://www.cpb.nl/en/staff/rudy-douven)
- [Ellis, Randy (US)](http://blogs.bu.edu/ellisrp/)
- [Glazer, Jacob (IS)](https://en-coller.tau.ac.il/profile/glazer)
- [Holly, Alberto (CH)](https://www.linkedin.com/in/alberto-holly-71555410)
- [Kauer, Lukas (CH)](https://www.unilu.ch/fakultaeten/gmf/professuren/lehr-und-forschungsbeauftragte/lukas-kauer-phd/)
- [Layton, Timothy (US)](https://hcp.hms.harvard.edu/people/timothy-j-layton)
- [Lorenz, Normann (DE)](https://www.uni-trier.de/universitaet/fachbereiche-faecher/fachbereich-iv/faecher/volkswirtschaftslehre/professuren/sozialpolitik/personen/prof-dr-normann-lorenz/forschung)
- [McGuire, Thomas (US)](http://www.hcp.med.harvard.edu/faculty/core/thomas-mcguire-phd)
- [Paolucci, Francesco (AU)](https://www.newcastle.edu.au/profile/francesco-paolucci)
- [Pirktl, Lenny (CH)](https://www.linkedin.com/in/lenny-pirktl-18835827)
- [Rose, Sherri (US)](https://profiles.stanford.edu/sherrirose)
- [Schillo, Sonja (DE)](https://www.linkedin.com/in/sonja-schillo-8b18a810/)
- [Schmid, Christian (CH)](https://www.css.ch/en/institute/about-us/team/christian-schmid.html)
- [Schokkaert, Erik (BE)](http://www.kuleuven.be/wieiswie/nl/person/00009398)
- [Schut, Erik (NL)](https://www.eur.nl/eshpm/people/erik-schut)
- [Shmueli, Amir (IS)](https://www.israelhpr.org.il/en/organization/prof-amir-shmueli/)
- [Stam, Piet (NL)](https://research.vu.nl/en/persons/piet-stam)
- [Van de Ven, Wynand (NL)](https://www.eur.nl/eshpm/people/wynand-van-de-ven)
- [Van Kleef, Richard (NL)](https://www.eur.nl/eshpm/people/richard-van-kleef)
- [Van Veen, Suzanne (NL)](https://www.linkedin.com/in/suzanne-van-veen-wubben-93961119)
- [Van Vliet, René (NL)](https://www.eur.nl/eshpm/people/rene-van-vliet/)
- [Wasem, Juergen (DE)](https://www.mm.wiwi.uni-due.de/team/lehrstuhlinhaber/juergen-wasem/)
- [Withagen-Koster, Anja (NL)](https://www.eur.nl/eshpm/people/anja-withagen-koster)

# Profile of permanent guest

- [Demme, Sylvia](https://www.linkedin.com/in/dr-sylvia-demme-1b5457113/)
